In [1]:
import pandas as pd
import numpy as np

In [97]:
def recomendacion_juego(item_id):
    df = pd.read_json("DataSets/df_modelo.json")
    columnas = df.columns.tolist()

    # Determino las caracteristicas relevantes de cada item
    caracteristicas = df[columnas].values
    # Determino las caracteristicas del item ingresado
    caract_item = df[df.index == item_id].values[0]

    # Calculo la similitud del coseno con los otros items
    similitudes = np.dot(caracteristicas, caract_item) / (np.linalg.norm(caracteristicas, axis=1) * 
                                                          np.linalg.norm(caract_item))
    
    # agrego al df una columna que indique las similitudes de cada item con el item ingresado
    df['Similitudes'] = similitudes

    # Ordeno los items por similitud en orden descendente
    df = df.sort_values(by='Similitudes', ascending=False)

    return df.index[1:6].tolist()

In [98]:
recomendacion_juego(10)

[6900, 13240, 3730, 6910, 38460]

In [68]:
df = pd.read_json("DataSets/df_modelo.json")

In [43]:
df.head(1)

Action  Adventure  Casual  Indie  Massively Multiplayer  RPG  Racing  \
10       1          0       0      0                      0    0       0   

    Simulation  Sports  Strategy  ...  2011  2012  2013  2014  2015  2016  \
10           0       0         0  ...     0     0     0     0     0     0   

    2017  2018  2019  2021  
10     0     0     0     0  

[1 rows x 48 columns]

In [76]:
columnas = df.columns.tolist()

In [78]:
columnas_ = ['Action', 'Adventure', 'Casual', 'Indie', 'Massively Multiplayer',
       'RPG', 'Racing', 'Simulation', 'Sports', 'Strategy', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2021']

In [79]:
# Determino las caracteristicas relevantes
caracteristicas = df[columnas].values
caracteristicas

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [80]:
# Determino las caracteristicas del item ingresado
item = 10
caract_item = df[df.index == item].values[0]
caract_item

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [81]:
# corroboro que sean matrices multiplicables
caracteristicas.shape, caract_item.shape

((26681, 48), (48,))

In [82]:
# Calculo la similitud del coseno con los otros items
similitudes = np.dot(caracteristicas, caract_item) / (np.linalg.norm(caracteristicas, axis=1) * np.linalg.norm(caract_item))

In [83]:
similitudes

array([1.        , 0.        , 0.5       , ..., 0.28867513, 0.        ,
       0.40824829])

In [84]:
# agrego una columna que indique las similotudes de cada item con el item ingresado
df['Similitudes'] = similitudes

In [85]:
df.head(2)

Action  Adventure  Casual  Indie  Massively Multiplayer  RPG  Racing  \
10         1          0       0      0                      0    0       0   
1002       0          0       0      1                      0    0       0   

      Simulation  Sports  Strategy  ...  2012  2013  2014  2015  2016  2017  \
10             0       0         0  ...     0     0     0     0     0     0   
1002           0       0         0  ...     0     0     0     0     0     0   

      2018  2019  2021  Similitudes  
10       0     0     0          1.0  
1002     0     0     0          0.0  

[2 rows x 49 columns]

In [86]:
# Ordeno los items por similitud en orden descendente
df = df.sort_values(by='Similitudes', ascending=False)

In [96]:
df.index[1:6].tolist()

[6900, 13240, 3730, 6910, 38460]

In [88]:
df.head(5)

Action  Adventure  Casual  Indie  Massively Multiplayer  RPG  Racing  \
10          1          0       0      0                      0    0       0   
6900        1          0       0      0                      0    0       0   
13240       1          0       0      0                      0    0       0   
3730        1          0       0      0                      0    0       0   
6910        1          0       0      0                      0    0       0   

       Simulation  Sports  Strategy  ...  2012  2013  2014  2015  2016  2017  \
10              0       0         0  ...     0     0     0     0     0     0   
6900            0       0         0  ...     0     0     0     0     0     0   
13240           0       0         0  ...     0     0     0     0     0     0   
3730            0       0         0  ...     0     0     0     0     0     0   
6910            0       0         0  ...     0     0     0     0     0     0   

       2018  2019  2021  Similitudes  
10        0     0     0          1.0  
6900      0     0     0          1.0  
13240     0     0     0          1.0  
3730      0     0     0          1.0  
6910      0     0     0          1.0  

[5 rows x 49 columns]